name: Whitesource Prioritize Java Android SDK with Gradle

on:
  push:
    branches: [ release* ]
  pull_request:
    branches: [ release* ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./android
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
      - name: Install Android SDK
        uses: malinskiy/action-android/install-sdk@release/0.1.1
      - name: Gradle Wrapper Validation
        uses: gradle/wrapper-validation-action@v1
      - name: Configure Gradle
        # Gradle configuration install deps
        run: ./gradlew help
      - name: Spot check
        run: ./gradlew spotlessCheck --stacktrace
      - name: Build Project
        run: ./gradlew assemble --stacktrace
      - name : Testing
        run: ./gradlew test --stacktrace
      - name: Final Checks
        run: ./gradlew check --stacktrace
