name: Whitesource Prioritize Java Android SDK with Gradle

on:
  push:
    branches: [ release* ]
  pull_request:
    branches: [ release* ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./android
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
      - name: Install Android SDK
        uses: malinskiy/action-android/install-sdk@release/0.1.1
      - name: Gradle Wrapper Validation
        uses: gradle/wrapper-validation-action@v1
      - name: Configure Gradle
        # Gradle configuration install deps
        run: ./gradlew help
      - name: Spot check
        run: ./gradlew spotlessCheck --stacktrace
      - name: Build Project
        run: ./gradlew assemble --stacktrace
      - name: WhiteSource Prioritize Scan
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          WS_APIKEY: ${{secrets.APIKEY}}
          WS_USERKEY: ${{secrets.USERKEY}}
        run: |
          cat <<EOF > eua.config
          apiKey=$WS_APIKEY
          userKey=$WS_USERKEY
          wss.url=https://saas.whitesourcesoftware.com/agent
          productName=GH_${{ github.event.repository.name }}
          projectName=${{ github.ref }}_Prioritize
          enableImpactAnalysis=true
          requireKnownSha1=false
          resolveAllDependencies=false
          gradle.resolveDependencies=true
          gradle.aggregateModules=true
          gradle.preferredEnvironment=wrapper
          gradle.wrapperPath=./gradlew
          fileSystemScan=false
          generateProjectDetailsJson=true
          EOF
          cat eua.config
          echo config created successfully
          curl -LJO https://unified-agent.s3.amazonaws.com/wss-unified-agent.jar
          curl -LJO https://unified-agent.s3.amazonaws.com/xModuleAnalyzer/xModuleAnalyzer.jar
          echo Unified Agent downloaded successfully
          java -jar wss-unified-agent.jar -d ./ -analyzeMultiModuleExclusions '**/*docs*' -analyzeMultiModule multimodule.txt
          echo 'multimodule.txt contents'
          cat multimodule.txt
          java -jar xModuleAnalyzer.jar -xModulePath multimodule.txt -fsaJarPath ./wss-unified-agent.jar -c ./eua.config -aggregateModules true -viaDebug true
      - name: 'Upload Prioritize Logs'
        uses: actions/upload-artifact@v2
        with:
          name: Prioritize-Logs
          path: |
            ${{github.workspace}}/whitesource
            /tmp/whitesource*
            /tmp/ws-ua*
          retention-days: 1


